# Generated by Django 2.0.4 on 2018-09-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='reporter',
        ),
        migrations.AddField(
            model_name='gallery',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Image'),
        ),
    ]
